### ISSUE TITLE
 Unable to determine Swift version for the following pods

### ISSUE THREAD

**Issue by 179992096** [nordicsemi/IOS-DFU-Library#276] opened 2019-03-05 03:47 UTC
[!] Unable to determine Swift version for the following pods:

- `Zip` does not specify a Swift version and none of the targets (`Cheetah`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

**Comment by philips77** [comment] 2019-03-05 21:22
Duplicate of #268.

**Closed as completed by philips77** 2019-03-05 21:23 UTC
